site_name: Python AppImage
site_description: AppImage distributions of Python
site_author: Valentin Niess
copyright: GPL-3.0

repo_url: https://github.com/niess/python-appimage/
edit_uri: edit/master/docs/src

docs_dir: src

nav:
  - Python AppImages: index.md
  - Developers' corner: apps.md

theme:
  name: readthedocs
  navigation_depth: 3
  highlightjs: no

plugins:
  - macros:
      include_dir: docs/include
      module_name: include/macros
  - search

markdown_extensions:
  - admonition
  - md_in_html

extra_css: [css/extra.css, css/nord.min.css]

extra_javascript: [js/apps.js, js/highlight.min.js, js/index.js]

extra:
  github_api:
    releases: https://api.github.com/repos/niess/python-appimage/releases
