name: Applications
on:
  push:
    paths:
    - '.github/workflows/applications.yml'
    - 'applications/**'
    - 'python_appimage/**'

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['2.7', '3.7', '3.9']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.version }}

    - name: Test scipy
      run: |
        python -m python_appimage build app applications/scipy                 \
                                            --python-version=2.7               \
                                            --python-tag=cp27-cp27mu
        test -e scipy-x86_64.AppImage
        ./scipy-x86_64.AppImage -c 'import numpy, pandas, scipy'

    - name: Test tasmotizer
      run: |
        python -m python_appimage build app applications/tasmotizer            \
                                            --linux-tag=manylinux2014_x86_64
        test -e tasmotizer-x86_64.AppImage

    - name: Test xonsh
      run: |
        python -m python_appimage build app applications/xonsh
        test -e xonsh-x86_64.AppImage
        ./xonsh-x86_64.AppImage -c 'import xonsh'

    - name: Test ssh-mitm
      if: ${{ matrix.version == '3.9' }}
      run: |
        python -m python_appimage build app applications/ssh-mitm
        test -e ssh-mitm-x86_64.AppImage
        ./ssh-mitm-x86_64.AppImage --help
